// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12QBvI7hIEk0JkQUb3CK5Op1S-mHcdx8',
    appId: '1:837313314545:web:61fe81bb68734ace663350',
    messagingSenderId: '837313314545',
    projectId: 'tg-app-88324',
    authDomain: 'tg-app-88324.firebaseapp.com',
    storageBucket: 'tg-app-88324.firebasestorage.app',
    measurementId: 'G-GNDE1BVKXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7TEunNCNXxMX2qYTqxvs7idVlyA9p76o',
    appId: '1:837313314545:android:9e43b19ec3d11a68663350',
    messagingSenderId: '837313314545',
    projectId: 'tg-app-88324',
    storageBucket: 'tg-app-88324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQXWgzCf7jBjLFgjDjecTmyQwcgfcAxY',
    appId: '1:837313314545:ios:0a98327332685b6c663350',
    messagingSenderId: '837313314545',
    projectId: 'tg-app-88324',
    storageBucket: 'tg-app-88324.firebasestorage.app',
    iosBundleId: 'com.example.tgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQXWgzCf7jBjLFgjDjecTmyQwcgfcAxY',
    appId: '1:837313314545:ios:0a98327332685b6c663350',
    messagingSenderId: '837313314545',
    projectId: 'tg-app-88324',
    storageBucket: 'tg-app-88324.firebasestorage.app',
    iosBundleId: 'com.example.tgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB12QBvI7hIEk0JkQUb3CK5Op1S-mHcdx8',
    appId: '1:837313314545:web:aef4ec5911bedb85663350',
    messagingSenderId: '837313314545',
    projectId: 'tg-app-88324',
    authDomain: 'tg-app-88324.firebaseapp.com',
    storageBucket: 'tg-app-88324.firebasestorage.app',
    measurementId: 'G-HF81MK959J',
  );
}
